### ISSUE TITLE
User does not have sufficient permission

### ISSUE THREAD

**Issue by Sawascwoolf** [PromInc/organic-search-analytics#2]
```
Fatal error: Uncaught exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/webmasters/v3/sites/praktikumbserichte.eu/searchAnalytics/query: (403) User does not have sufficient permission for site 'http://praktikumbserichte.eu/'. See also: https://support.google.com/webmasters/answer/2451999.' in /var/www/web61/html/example.com/googleApi/organic-search-analytics-master/apis/Google/Http/REST.php:110 Stack trace: #0 /var/www/web61/html/example.com/googleApi/organic-search-analytics-master/apis/Google/Http/REST.php(62): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client)) #1 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request)) #2 /var/www/web61/html/example.com/googleApi/organic-search-analytics-master/apis/Google/Task/Runner.php(174): call_user_func_array(Array, Array) #3 /var/www/web61/html/example.com/googleApi/organic-search-analytics-master/apis/Google/Http/REST.php(46): Google_Task_Runner->run() #4 in /var/www/web61/html/example.com/googleApi/organic-search-analytics-master/apis/Google/Http/REST.php on line 110
```

I`ve followed all of your steps mentioned in the readme and I double checked adding the correct email to the allowed users in the search console itself.

Do you have any suggestions?

**Comment by Sawascwoolf** [comment]
Blame me :(
Misspelled my website

**Comment by PromInc** [comment]
Also, just this morning I pushed out a release that pulls in the list of sites from Google Search Console as opposed to manually entering in the sites.  You'll still need to check which sites you want to enable on the Settings page, but this should prevent this error from happening again.

And don't worry, you're not the only one that has made this mistake.... I have as well...  hence one of the many reasons for the new release.
